### ISSUE TITLE
better name for tool

### ISSUE THREAD

**Issue by jlovejoy** [spdx/spdx-license-diff#5]
consider a better name as there is already an SPDX diff tool for comparing full SPDX documents.

**Comment by swinslow** [comment]
what-license-is-this  

=)

**Comment by jlovejoy** [comment]
> @jlovejoy I couldn't find a link to the tool with the conflict. Can you please post?

good question, I think it's this: http://13.57.134.254/app/compare/ 
@goneall or @zvr could one of you comment here?

**Comment by goneall** [comment]
I think what was being referenced was the compare command/feature/menu item in the [SPDX online tool](https://github.com/spdx/spdx-online-tools) and the [SPDX command line](https://github.com/spdx/tools) tools.

To make it even more confusing, these tools support a license compare feature and an SPDX document compare feature.

If my understanding is correct, using spdx-diff may be OK as the name isn't being used by an existing SPDX tool.

**Comment by zvr** [comment]
My take is that we are a small group of people that deal with SPDX licenses (their identifiers, texts, and intricacies) every day and we obviously understand what is meant.
On the other hand I try, when using the term "SPDX", to refer to the complete thing (spec, documents, etc.). If someone says "we're using SPDX" I hope they mean something more than "we put `SPDX-License-Identifier` lines in our files."

Therefore, I would really prefer this functionality to have a more precise name.

Something like "license-match" or "_SPDX-License-Matcher_" or ... (no one will type this as a command, anyway).

In any case, thanks @alandtse for a great tool!

**Comment by alandtse** [comment]
While I like SPDX License Matcher we'd be pretty close to an existing tool, [spdx-license-match](https://github.com/rohieb/spdx-license-match). I'm hesitant to say license match without spdx because of the limited matching domain, (what about matching osi, etc.?)

If we go with the diff theme, it would be SPDX License Diff, but then I wonder if the name would need to change if we implement other things like exception matching. I also wonder if SPDX will want to do their own clearance on the name and I'd defer to that decision. @swinslow where do we stand at getting this hosted by SPDX?

**Comment by swinslow** [comment]
+1 on "SPDX License Diff." I'm good with this name even if it's expanded to include exception matching. We tend to use e.g. "SPDX License List" broadly as a reference to include the exceptions list as well.

A few thoughts on next steps:

1) @alandtse , are you good with "SPDX License Diff" and with "spdx-license-diff" as the repo name?

2) @goneall , after Alan confirms on the name, can you create an empty repo in the github.com/spdx org with the chosen repo name, and provide Alan with upload access?

3) @alandtse , after Gary creates the repo, it would be great if you could push the existing codebase there. I'd suggest perhaps adding it as a single initial commit without the existing commit history, and include a "Signed-off-by:" line in the commit message, if the prior commits haven't had DCO sign-offs.

4) We'll also want to add (1) a LICENSE file with the current GPL-3.0 license text, and (2) a CONTRIBUTING file that makes it clear what the intended future license will be. There's a bit of a challenge in that if we're going with GPL-3.0 for now (b/c of the SO code) but plan to switch to a different license later, then any contributions from third parties in the interim would be made under GPL-3.0 -- and would need relicensing permissions later.

I'd suggest we also go ahead and decide what the future license will be (Apache-2.0, to match the main SPDX tools?) and state in the CONTRIBUTING file that any contributions must include a statement that they are dual-licensed under GPL-3.0 and Apache-2.0. I don't want to over-engineer this, but just conscious of the complications given the current and future license stance.

5) I'll be working with the LF IT team to figure out what's workable, in terms of providing an official extension in the Chrome store. For the projects I've worked on, we more typically provide source code rather than compiled / binaries. I'm not aware of prior ones where we've built and pushed a Chrome extension to their store, so it may take a bit longer to sort through this part (especially given the upcoming holidays). But I don't think this needs to block moving the source code into the main SPDX repo.

**Comment by goneall** [comment]
Once we have confirmation on the name, I'll create the empty repo.

I did have a question on the licensing - I believe the stack overflow license is actually CC-BY-SA rather than GPL 3.0.  Should we go with that for the overall licensing?

**Comment by goneall** [comment]
@swinslow You make a good point on the license and contributing.  I would like to have more permissive licenses myself.  Either Apache-2.0 or MIT would be good choices in my (non-lawyer) opinion.

**Comment by alandtse** [comment]
Also this is the link for Google Group publishing. https://developer.chrome.com/webstore/publish#set-up-group-publishing.  We can move it there and others can have publish rights.

**Comment by alandtse** [comment]
@swinslow All prior commits are signed already.
@goneall For me to do the transfer, the repo can't already exist in the target org and I need repo creation rights in the org.

**Comment by alandtse** [comment]
@goneall Gary, whenever you're ready for me to transfer the repo please give me repo creating privileges on SPDX so I can do the transfer. I removed the empty repo since you can't do a transfer if an existing repo conflicts.

**Comment by goneall** [comment]
@alandtse You should have full access to transfer the repo.

**Comment by alandtse** [comment]
@goneall Transferred. You can revert my access if you need to.

**Comment by alandtse** [comment]
Closing this as the name issue is resolved. We can open another ticket to address other transfer issues.
